# Generated by Django 5.2 on 2025-06-03 20:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('diabetes', 'Diabète'), ('hypertension', 'Hypertension'), ('general', 'Général')], max_length=20, verbose_name='Catégorie')),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('document', 'Document'), ('video', 'Vidéo'), ('website', 'Site web')], max_length=20, verbose_name='Type de ressource')),
                ('format_type', models.CharField(choices=[('file', 'Fichier'), ('link', 'Lien externe')], default='file', max_length=10, verbose_name='Format')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/files/', verbose_name='Fichier')),
                ('url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-created_at'],
            },
        ),
    ]
